apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"tasky-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"tasky"}},"template":{"metadata":{"labels":{"app":"tasky"}},"spec":{"containers":[{"env":[{"name":"MONGODB_URI","value":"mongodb://mongodbuser:password@18.220.195.173:27017/go-mongodb"}],"image":"920373025326.dkr.ecr.us-east-2.amazonaws.com/tasky:latest","name":"tasky","ports":[{"containerPort":8080}],"securityContext":{"runAsUser":0}}]}}}}
  creationTimestamp: "2025-05-14T22:59:11Z"
  generation: 8
  name: tasky-deployment
  namespace: default
  resourceVersion: "62996"
  uid: afa600f8-17f9-4c1a-be4f-02644a224938
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tasky
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-14T21:11:38-04:00"
      creationTimestamp: null
      labels:
        app: tasky
    spec:
      containers:
      - env:
        - name: MONGODB_URI
          value: mongodb://mongodbuser:password@18.220.195.173:27017/go-mongodb
        image: 920373025326.dkr.ecr.us-east-2.amazonaws.com/tasky:latest
        imagePullPolicy: Always
        name: tasky
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-05-15T01:27:47Z"
    lastUpdateTime: "2025-05-15T01:27:47Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-05-15T01:27:46Z"
    lastUpdateTime: "2025-05-15T01:34:04Z"
    message: ReplicaSet "tasky-deployment-59785fb888" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 8
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
