AWSTemplateFormatVersion: '2010-09-09'
Description: Basic VPC Stack for Tasky App

Resources:
  TaskyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: tasky-vpc

Outputs:
  VPCId:
    Description: The ID of the VPC
    Value: !Ref TaskyVPC
