name: Deploy CloudFormation Stack

on:
  push:
    paths:
      - 'cloudformation/**'
      - '.github/workflows/deploy-infra.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/vpc-stack.yaml \
          --stack-name tasky-vpc-stack \
          --capabilities CAPABILITY_NAMED_IAM

